running with extra stuff
❯ npm run node

> mina@0.0.0 node
> node main.js

/Users/laptop/Development/01-Learning/transcription/mina/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: dlopen(/Users/laptop/Development/01-Learning/transcription/mina/build/Release/addon.node, 0x0001): symbol not found in flat namespace '_dequantize_row_iq1_m'
    at Module._extensions..node (node:internal/modules/cjs/loader:1454:18)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
    at bindings (/Users/laptop/Development/01-Learning/transcription/mina/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/laptop/Development/01-Learning/transcription/mina/main.js:1:51)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Module.load (node:internal/modules/cjs/loader:1208:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v20.15.0
❯ cat whisper.cpp/ggml/src/ggml-quants.c | grep dequantize_row_iq1_m
void dequantize_row_iq1_m(const block_iq1_m * restrict x, float * restrict y, int64_t k) {
❯ npm run clean; npm run rebuild;

> mina@0.0.0 clean
> node-gyp clean

gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.15.0 | darwin | arm64
gyp info ok

> mina@0.0.0 rebuild
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@20.15.0 | darwin | arm64
gyp info find Python using Python version 3.10.10 found at "/opt/homebrew/Caskroom/miniconda/base/bin/python3"

gyp info spawn /opt/homebrew/Caskroom/miniconda/base/bin/python3
gyp info spawn args [
gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/Users/laptop/Development/01-Learning/transcription/mina/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/Users/laptop/Library/Caches/node-gyp/20.15.0/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/Users/laptop/Library/Caches/node-gyp/20.15.0',
gyp info spawn args '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/Users/laptop/Library/Caches/node-gyp/20.15.0/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/Users/laptop/Development/01-Learning/transcription/mina',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
  LIBTOOL-STATIC Release/nothing.a
warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
  CC(target) Release/obj.target/addon/whisper.cpp/ggml/src/ggml.o
../whisper.cpp/ggml/src/ggml.c:1944:20: warning: unused function 'ggml_vec_dot_f16_unroll' [-Wunused-function]
inline static void ggml_vec_dot_f16_unroll(const int n, const int xs, float * restrict s, void * restrict xv, ggml_fp16_t * restrict y) {
                   ^
../whisper.cpp/ggml/src/ggml.c:2196:20: warning: unused function 'ggml_vec_gelu_f16' [-Wunused-function]
inline static void ggml_vec_gelu_f16(const int n, ggml_fp16_t * y, const ggml_fp16_t * x) {
                   ^
../whisper.cpp/ggml/src/ggml.c:2917:17: warning: unused function 'ggml_get_numa_affinity' [-Wunused-function]
static uint32_t ggml_get_numa_affinity(void) {
                ^
../whisper.cpp/ggml/src/ggml.c:3308:19: warning: unused function 'ggml_up32' [-Wunused-function]
static inline int ggml_up32(int n) {
                  ^
../whisper.cpp/ggml/src/ggml.c:19482:13: warning: unused function 'ggml_opt_get_grad' [-Wunused-function]
static void ggml_opt_get_grad(int np, struct ggml_tensor * const ps[], float * g) {
            ^
5 warnings generated.
  CC(target) Release/obj.target/addon/whisper.cpp/ggml/src/ggml-alloc.o
../whisper.cpp/ggml/src/ggml-alloc.c:467:13: warning: unused function 'ggml_gallocr_set_node_offset' [-Wunused-function]
static void ggml_gallocr_set_node_offset(ggml_gallocr_t galloc, struct ggml_tensor * node, int buffer_id, size_t offset) {
            ^
1 warning generated.
  CC(target) Release/obj.target/addon/whisper.cpp/ggml/src/ggml-backend.o
  CC(target) Release/obj.target/addon/whisper.cpp/ggml/src/ggml-quants.o
../whisper.cpp/ggml/src/ggml-quants.c:1767:14: warning: unused function 'make_qkx1_quants' [-Wunused-function]
static float make_qkx1_quants(int n, int nmax, const float * restrict x, uint8_t * restrict L, float * restrict the_min,
             ^
../whisper.cpp/ggml/src/ggml-quants.c:13752:12: warning: unused function 'iq1_find_best_neighbour' [-Wunused-function]
static int iq1_find_best_neighbour(const uint16_t * restrict neighbours, const uint64_t * restrict grid,
           ^
2 warnings generated.
  CXX(target) Release/obj.target/addon/whisper.cpp/src/whisper.o
../whisper.cpp/src/whisper.cpp:225:29: warning: unused function 'ggml_mul_mat_pad' [-Wunused-function]
static struct ggml_tensor * ggml_mul_mat_pad(struct ggml_context * ctx, struct ggml_tensor * x, struct ggml_tensor * y, int pad = 32) {
                            ^
1 warning generated.
  CXX(target) Release/obj.target/addon/native/stt_whisper.o
  CXX(target) Release/obj.target/addon/native/addon.o
  SOLINK_MODULE(target) Release/addon.node
gyp info ok
❯ npm run node

> mina@0.0.0 node
> node main.js

whisper_init_from_file_with_params_no_state: loading model from '/Users/laptop/Development/01-Learning/transcription/mina/whisper.cpp/models/ggml-tiny.en.bin'
whisper_init_with_params_no_state: use gpu    = 1
whisper_init_with_params_no_state: flash attn = 0
whisper_init_with_params_no_state: gpu_device = 0
whisper_init_with_params_no_state: dtw        = 0
whisper_model_load: loading model
whisper_model_load: n_vocab       = 51864
whisper_model_load: n_audio_ctx   = 1500
whisper_model_load: n_audio_state = 384
whisper_model_load: n_audio_head  = 6
whisper_model_load: n_audio_layer = 4
whisper_model_load: n_text_ctx    = 448
whisper_model_load: n_text_state  = 384
whisper_model_load: n_text_head   = 6
whisper_model_load: n_text_layer  = 4
whisper_model_load: n_mels        = 80
whisper_model_load: ftype         = 1
whisper_model_load: qntvr         = 0
whisper_model_load: type          = 1 (tiny)
whisper_model_load: adding 1607 extra tokens
whisper_model_load: n_langs       = 99
whisper_model_load:      CPU total size =    77.11 MB
whisper_model_load: model size    =   77.11 MB
whisper_mel_init: n_len = 6000, n_len_org = 6000, n_mel = 80
whisper_init_state: kv self size  =    9.44 MB
whisper_init_state: kv cross size =    9.44 MB
whisper_init_state: kv pad  size  =    2.36 MB
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: reallocating buffers automatically
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 11.08 MiB
whisper_init_state: compute buffer (conv)   =   13.19 MB
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: reallocating buffers automatically
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 80.06 MiB
whisper_init_state: compute buffer (encode) =   85.53 MB
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: reallocating buffers automatically
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 2.20 MiB
whisper_init_state: compute buffer (cross)  =    3.88 MB
ggml_gallocr_needs_realloc: graph has different number of nodes
ggml_gallocr_alloc_graph: reallocating buffers automatically
ggml_gallocr_reserve_n: reallocating CPU buffer from size 0.00 MiB to 89.95 MiB
whisper_init_state: compute buffer (decode) =   95.89 MB
Whisper model loaded successfully. Starting transcription...
Listening to your microphone. Speak now...
Press Ctrl+C to stop.
WAV format: {
  audioFormat: 1,
  endianness: 'LE',
  channels: 1,
  sampleRate: 16000,
  byteRate: 32000,
  blockAlign: 2,
  bitDepth: 16,
  signed: true
}
whisper_mel_init: n_len = 3051, n_len_org = 50, n_mel = 80
whisper_full_with_state: input is too short - 500 ms < 1000 ms. consider padding the input audio with silence
whisper_mel_init: n_len = 3102, n_len_org = 102, n_mel = 80
whisper_mel_init: n_len = 3153, n_len_org = 153, n_mel = 80
whisper_mel_init: n_len = 3204, n_len_org = 204, n_mel = 80
whisper_mel_init: n_len = 3255, n_len_org = 255, n_mel = 80
whisper_mel_init: n_len = 3307, n_len_org = 306, n_mel = 80
whisper_mel_init: n_len = 3358, n_len_org = 358, n_mel = 80
whisper_mel_init: n_len = 3409, n_len_org = 409, n_mel = 80
whisper_mel_init: n_len = 3460, n_len_org = 460, n_mel = 80
whisper_mel_init: n_len = 3511, n_len_org = 511, n_mel = 80
whisper_mel_init: n_len = 3563, n_len_org = 562, n_mel = 80
speech end detected
Transcribed and copied to clipboard:  Hello, hello, hello.
whisper_mel_init: n_len = 3101, n_len_org = 100, n_mel = 80
whisper_mel_init: n_len = 3152, n_len_org = 152, n_mel = 80
whisper_mel_init: n_len = 3203, n_len_org = 203, n_mel = 80
whisper_mel_init: n_len = 3254, n_len_org = 254, n_mel = 80
whisper_mel_init: n_len = 3306, n_len_org = 305, n_mel = 80
whisper_mel_init: n_len = 3357, n_len_org = 356, n_mel = 80
whisper_mel_init: n_len = 3408, n_len_org = 408, n_mel = 80
whisper_mel_init: n_len = 3459, n_len_org = 459, n_mel = 80
whisper_mel_init: n_len = 3510, n_len_org = 510, n_mel = 80
whisper_mel_init: n_len = 3562, n_len_org = 561, n_mel = 80
whisper_mel_init: n_len = 3613, n_len_org = 612, n_mel = 80
whisper_mel_init: n_len = 3664, n_len_org = 664, n_mel = 80
whisper_mel_init: n_len = 3715, n_len_org = 715, n_mel = 80
whisper_mel_init: n_len = 3766, n_len_org = 766, n_mel = 80
whisper_mel_init: n_len = 3818, n_len_org = 817, n_mel = 80
whisper_mel_init: n_len = 3869, n_len_org = 868, n_mel = 80
whisper_mel_init: n_len = 3920, n_len_org = 920, n_mel = 80
whisper_mel_init: n_len = 3971, n_len_org = 971, n_mel = 80
whisper_mel_init: n_len = 4022, n_len_org = 1022, n_mel = 80
whisper_mel_init: n_len = 4074, n_len_org = 1073, n_mel = 80
whisper_mel_init: n_len = 4125, n_len_org = 1124, n_mel = 80
whisper_mel_init: n_len = 4176, n_len_org = 1176, n_mel = 80
whisper_mel_init: n_len = 4227, n_len_org = 1227, n_mel = 80
whisper_mel_init: n_len = 4278, n_len_org = 1278, n_mel = 80
whisper_mel_init: n_len = 4330, n_len_org = 1329, n_mel = 80
whisper_mel_init: n_len = 4381, n_len_org = 1380, n_mel = 80
whisper_mel_init: n_len = 4432, n_len_org = 1432, n_mel = 80
Transcribed and copied to clipboard:  [ Pause ]
whisper_mel_init: n_len = 3101, n_len_org = 100, n_mel = 80
whisper_mel_init: n_len = 3152, n_len_org = 152, n_mel = 80
whisper_mel_init: n_len = 3203, n_len_org = 203, n_mel = 80
whisper_mel_init: n_len = 3254, n_len_org = 254, n_mel = 80
whisper_mel_init: n_len = 3306, n_len_org = 305, n_mel = 80
whisper_mel_init: n_len = 3357, n_len_org = 356, n_mel = 80
whisper_mel_init: n_len = 3408, n_len_org = 408, n_mel = 80
whisper_mel_init: n_len = 3459, n_len_org = 459, n_mel = 80
whisper_mel_init: n_len = 3510, n_len_org = 510, n_mel = 80
whisper_mel_init: n_len = 3562, n_len_org = 561, n_mel = 80
whisper_mel_init: n_len = 3613, n_len_org = 612, n_mel = 80
whisper_mel_init: n_len = 3664, n_len_org = 664, n_mel = 80
whisper_mel_init: n_len = 3715, n_len_org = 715, n_mel = 80
whisper_mel_init: n_len = 3766, n_len_org = 766, n_mel = 80
whisper_mel_init: n_len = 3818, n_len_org = 817, n_mel = 80
whisper_mel_init: n_len = 3869, n_len_org = 868, n_mel = 80